GET http://localhost:4000/post
###
GET http://localhost:4000/post/12

####

POST  http://localhost:4000/post
Content-Type: application/json

{
    "name":"test2",
    "title":"title2",
    "description":"description2"
}

###

GET http://localhost:4000/post/6454fec9c4e9f49f74e033a9


###

DELETE  http://localhost:4000/post/6454fec9c4e9f49f74e033a9
